on:
  push:
    branches:
      - main

jobs:
  gh-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v3
      - name: install dependencies
        run: nimble install -y
      - name: Compile Book
        run: nim c getting_started.nim
      - name: Init Book
        run: ./getting_started init
      - name: Build Book
        run: ./getting_started build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
