name: valid

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Show pending status check
        uses: Sibz/github-status-action@v1.1.5
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          sha: ${{ github.event.pull_request.head.sha }}
          description: Waiting for build to finish
          state: pending
      
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v3
      - run: nimble install -y
      - name: GenBook
        run: nimble genbook
      - run: echo Commit hash = ${{ github.event.pull_request.head.sha }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ github.event.pull_request.head.sha }}
          path: docs/
          retention-days: 1
          if-no-files-found: error

